### PR TITLE
Make spec more readable

### PR DESCRIPTION
**Pull request by stereobooster**
before

screen shot 2017-04-08 at 09 03 04

after

screen shot 2017-04-08 at 09 02 41

### CODE REVIEW

**Comment by tydeu** [comment]
Hahaha! I just did essentially the same thing. It frustrated me so much I fiddle with it in GitHub's file edit feature and then decided to submit it as a pull request. I never thought to check if someone had already done something similar.

However, you just deleted the anchors instead of fixing them, which means in your version you can't use the table of contents to navigate anymore.

**Comment by stereobooster** [comment]
@tydeu it can. See yourself https://github.com/stereobooster/msgpack/blob/4f79c43b1a480e90ad173f93423f35602507678b/spec.md

**Comment by tydeu** [comment]
Huh... Guess I was wrong.

**Comment by tagomoris** [comment]
I'm so sorry for late reply. Now this pull-request conflicts the latest spec.
I merged this change as #234.
Thank you!

**Pull request closed without merging**
